### ISSUE TITLE
我又来啦。测试生成的Mysql和Oracle的SQL语句，有以下问题，麻烦帮忙看看，谢谢！

### ISSUE THREAD

**Issue by lishuangquan1987** [zqlovejyc/SQLBuilder#5]
**生成的Oracle数据库的问题：**
1.【BUG】生成的sql语句的表名和列带有引号，放到Oracle连接工具中执行会报错，表名带引号没问题，列不能带引号。例如生成的oracle SQL语句如下：
SELECT * FROM "Base_UserInfo" A WHERE A."userId" > :Param0 OR A."Email" <> :Param1
其中userId,Email都不能带引号，sql语句才能正确执行
2.【BUG】Console测试group by第一个的代码：
```
Print(
                SqlBuilder.Select<UserInfo>()
                          .Where(o => o.Name == "张强")
                          .GroupBy(u => u.Id),
                "GroupBy分组查询 用法1",
                "GroupBy"
            );
```
生成的SQL语句：SELECT * FROM AAA_TEST_A_COPY A WHERE A.Name = :Param0 GROUP BY A.Id,
最后多了一个逗号，执行会报错，测试Oracle,Mysql都会有这个问题。
![image](https://user-images.githubusercontent.com/15365329/78090488-d9b9b280-73fc-11ea-8db3-1f87691208ce.png)

3.【可能不是BUG】group by语句，oracle数据库的group by语句要求比较奇怪，要求select多少个字段，group by 后面必须跟多少个字段。否则会报错。示例：SQLBuilder设置数据库为Oralce生成的group by语句如下：
GroupBy分组查询 用法1
SELECT * FROM AAA_TEST_A_COPY A WHERE A.Name = :Param0 GROUP BY A.Id,A.C_Nvarchar2
[:Param0, 张强]
将这个语句放到oracle连接工具中执行，会报这个错误：ORA-00936: 缺失表达式。把SQL语句修改为：
SELECT  A.Id,A.C_Nvarchar2 FROM AAA_TEST_A_COPY A WHERE A.Name = :Param0 GROUP BY A.Id,A.C_Nvarchar2
然后就不报错了
4.【BUG】oracle的insert语句，当插入的对象是数组时，生成的sql语句：
插入数据 用法6
INSERT INTO AAA_TEST_A_COPY (Name,Age,CreatedTime,Price,C_Number,C_Image,C_Char,C_Nvarchar2,C_TimeStamp) SELECT :Param0,:Param1,NULL,NULL,NULL,NULL,NULL,NULL,NULL FROM DUAL UNION ALL SELECT :Param2,:Param3,NULL,NULL,NULL,NULL,NULL,NULL,NULL FROM DUAL
[:Param0, 张三]
[:Param1, 2]
[:Param2, 张三]
[:Param3, 2]
dapper检测sql语句NG,原因：ORA-00918: 未明确定义列
将sql语句放到Oracle连接工具中执行也一样报这个错误：
![image](https://user-images.githubusercontent.com/15365329/78090899-04f0d180-73fe-11ea-9393-381793d4c7f4.png)
**生成的Mysql数据库的问题：**
【可能不是BUG】
Mysql数据库没有full join关键字，所以用full join生成的mysql sql语句执行会报错。

**Comment by zqlovejyc** [comment]
问题1：采用如下方式可以解决，原因是Oracle表和列添加“”格式后，必须保持大写的；
![image](https://user-images.githubusercontent.com/19462884/78093814-9e6fb180-7405-11ea-9e6c-30c07f941790.png)

问题2：bug已修复，请查看更新；

问题3：这个不能说是框架的问题了，这个需要自己灵活使用了；

问题4：应该是你列名的问题，我看提示“未明确定义列”，我试了下如下，可以正常使用
![image](https://user-images.githubusercontent.com/19462884/78093955-ea225b00-7405-11ea-85d8-0492129c9a07.png)

问题5：Mysql里面没有FULL JOIN语法 这个需要使用期间不采用这个语法了，框架本身的目的也是解析出来正确的sql语句；

**Comment by lishuangquan1987** [comment]
**针对问题1**，都加上标签，将列名转换为大写，这样很麻烦。能不能在获取列名时，自动将其转换为大写，还有，如下代码，针对oracle数据库，也存在大小写转换问题：
```
Print(
                SqlBuilder.Select<UserInfo>()
                          .OrderBy(u => new[] { "Id", "age" }, OrderType.Ascending, OrderType.Descending),
                "OrderBy排序 用法1-1",
                "OrderBy"
            );
```
![image](https://user-images.githubusercontent.com/15365329/78100256-d7645200-7416-11ea-9b64-4c61e6e77814.png)

**Comment by zqlovejyc** [comment]
不能说只针对Oracle进行全部大写，你可以把解析成的sql自己ToUpper一下即可；或者说在SqlIntercept这个拦截里面转换为大写；

**Comment by lishuangquan1987** [comment]
谢谢你的解答，目前没有其他问题了
